version: '3'
services:
  crawler:
    build:
      dockerfile: ./crawler/Dockerfile
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432
    restart: always
    volumes:
      - ./:./
