version: '3'
services:
  app :
    image: python:alpine
  db:
    image: postgres
    environment:
      - POSTGRES_USER=username
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=secret
  jupyter:
    image: jupyter/minimal-notebook
    restart: always